{0}{}{Spelinställningar}
{1}{}{Skärminställningar}
{50}{}{Skärminställningar}
{51}{}{Anpassad}
{52}{}{Bredd}
{53}{}{Höjd}
{54}{}{Klar}
{55}{}{Avbryt}
{56}{}{Fallout måste starta om för att tillämpa inställningarna.}
{57}{}{Vill du starta om Fallout nu?}
{58}{}{Sant}
{59}{}{Falskt}
{60}{}{}
{100}{}{Hög upplösning}
{101}{}{UPPLÖSNING}
{102}{}{Färger}
{103}{}{8 bitar}
{104}{}{16 bitar}
{105}{}{32 bitar}
{106}{}{Ändra sidofältskonst}
{107}{}{Invertera lista}
{108}{}{fönsterläge}
{109}{}{Ställ in bläddringsknapp}
{110}{}{Skalning X2}
{111}{}{Uppdateringsfrekvens}
{130}{}{Fönstertangent}
{131}{}{Välj}
{132}{}{Namn}
{140}{}{Grafikläge:}
{141}{}{Grundläggande}
{142}{}{Sfall DirectX 9-läge:}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Vertex hårdvarubearbetning:}
{149}{}{Shader version 2.0:}
{150}{}{Panelskalning}
{151}{}{Ingen}
{152}{}{Passa}
{153}{}{Fyll}
{154}{}{Filmer}
{155}{}{Stänk}
{156}{}{Hjälp}
{157}{}{Död}
{158}{}{Avslutningsbilder}
{159}{}{Huvudmeny}
{200}{}{Sfall}
{201}{}{SKALA-TILL: UPPLÖS.}
{202}{}{DX-9-LÄGE}
{203}{}{Av}
{204}{}{Fullskärm}
{205}{}{Fönster}
{206}{}{GPU-Blittning}
{207}{}{Denna inställning har ingen effekt när du är i Grundläggande grafik-läge.}
{250}{}{Ignorera PC:ns skrollgräns}
{253}{}{Sökintervallsavstånd}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Aktivera krigsdimma}
{257}{}{Sikt i dimma}
{258}{}{Mörk}
{259}{}{Ljusare}
{300}{}{TRYCK PÅ EN TANGENT eller ESC för att avbryta.}
{500}{}{Inställningar för Hi-Res Patch.}
{501}{}{Ställ in skärmupplösning, färgläge och uppdateringsfrekvens för fullskärmsläge.}
{502}{}{Ställ in helskärmens färgutmatning här.}
{503}{}{Ställ in uppdateringsfrekvensen i helskärmsläge här. Ställ in detta till '0' för standardinställningen för drivrutinen.}
{504}{}{Anpassa fullskärmsbredden genom att klicka på nummerrutan.}
{505}{}{Anpassa fullskärmshöjden genom att klicka på nummerrutan.}
{506}{}{Aktivera eller inaktivera fönsterläge.}
{507}{}{I fönsterläge är detta tangenten som du håller nedtryckt när du använder musen för att bläddra i spel- och världskartorna.}
{508}{}{Tryck på den röda knappen för att välja en annan tangent. Eller klicka på nummerrutan för att redigera koden för Windows Virtual Key.}
{509}{}{Namnet på den valda tangenten.}
{510}{}{Aktivera X2-skalning. Detta kommer också att öka minsta upplösningen till 1280x960. Fönsterläge kräver mer utrymme för sin ram.}
{511}{}{Aktivera eller inaktivera krigsdimma. För bästa resultat bör detta aktiveras innan du går in på en karta för första gången.}
{512}{}{Justera ljusnivån och musens 'titta på' synlighet för golv, väggar och landskap under dimman.}
{513}{}{Golv, väggar och dekor kommer alltid att vara synliga och musens "titta på" kommer att fungera normalt.}
{514}{}{Golv, väggar och dekor kommer att vara mörka och inte svara på musens "titta på" tills de upptäcks.}
{515}{}{När detta är aktiverat kan man obegränsat skrolla bort från spelarkaraktären. Detta fungerar bra om krigsdimma är aktiverat.}
{516}{}{Öka antalet söknoder för att förlänga sökavståndet. 20 nivåer i steg om 2000 noder.}
{517}{}{2000 noder för sökvägar (originalvärde). Obs: Varje nivå kräver ytterligare 156,25 KB minne.}
{518}{}{40 000 noder för sökvägar. Obs: kräver 3200000 byte (3125 KB) minne.}
{519}{}{Justera hur vissa skärmar ska visas.}
{520}{}{Originalstorlek.}
{521}{}{Utsträckt för att passa skärmens storlek samtidigt som det ursprungliga bildförhållandet bibehålls.}
{522}{}{Utsträckt för att fylla skärmen. Obs: Ett utrymme kommer att finnas kvar längst ner på skärmen om undertexter är aktiverade.}
{523}{}{Klicka nedan för att cykla i gränssnittet i spelets Side Bar-alternativ.}
{524}{}{Verkställ eventuella ändringar och avsluta.}
{525}{}{Avsluta utan att spara.}
