{0}{}{Ustawienia Gry}
{1}{}{Ustawienia Ekranu}
{50}{}{Ustawienia Ekranu}
{51}{}{Niestandardowe}
{52}{}{Szerokość}
{53}{}{Wysokość}
{54}{}{Gotowe}
{55}{}{Anuluj}
{56}{}{Uruchom ponownie, aby zastosować zmiany.}
{57}{}{Czy chcesz uruchomić ponownie?}
{58}{}{True}
{59}{}{False}
{60}{}{}
{100}{}{Hi-Res}
{101}{}{ROZDZIELCZOŚĆ}
{102}{}{Kolory}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Boczny panel}
{107}{}{Odwróć listę}
{108}{}{Okno}
{109}{}{Ustaw klawisz przewijania}
{110}{}{Skalowanie X2}
{111}{}{Odświeżanie}
{130}{}{Klawisz Trybu Okna}
{131}{}{Wybierz}
{132}{}{Nazwa}
{140}{}{Tryb grafiki:}
{141}{}{Podstawowy}
{142}{}{Tryb Sfall DirectX 9:}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}
{150}{}{Skalowanie elementu}
{151}{}{Wył.}
{152}{}{Dop.}
{153}{}{Wyp.}
{154}{}{Filmy}
{155}{}{Obraz}
{156}{}{Pomoc}
{157}{}{Śmierć}
{158}{}{Zakończenie}
{159}{}{Menu Główne}
{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{TRYB DX-9}
{203}{}{Wył.}
{204}{}{Pełny ekran}
{205}{}{Okno}
{206}{}{GPU Blitting}
{207}{}{To ustawienie nie ma zastosowania w trybie podstawowym.}
{250}{}{Ignoruj limit przewijania}
{253}{}{Zasięg szukania drogi}
{254}{}{Normalny}
{255}{}{Maksymalny}
{256}{}{Wł. mgłę wojny}
{257}{}{Widoczność mgły}
{258}{}{Ciemny}
{259}{}{Jasny}
{300}{}{Naciśnij klawisz A lub ESC aby anulować.}
{500}{}{Ustawienia Hi-Res Patch'a}
{501}{}{Ustawienia rozdzielczości ekranu, palety kolorów i odświeżania dla pełnego ekranu.}
{502}{}{Ustawienia palety kolorów dla pełnego ekranu.}
{503}{}{Ustawienia odświeżania dla pełnego ekranu. Ustaw "0" dla domyślnych ustawień sterownika.}
{504}{}{Dostosuj Szerokość przez wybór wartości.}
{505}{}{Dostosuj Wysokość przez wybór wartości.}
{506}{}{Wł. lub Wył. Tryb Okna.}
{507}{}{Naciśnięcie tego klawisza i przesuwanie myszką pozwala na przesuwanie obrazu.}
{508}{}{Wybór klawisza lub edycja kodu wirtualnego klawisza systemu Windows.}
{509}{}{Nazwa obecnie wybranego klawisza.}
{510}{}{Włącz skalowanie X2. Zmieni minimalną rozdzielczość na 1280x960.}
{511}{}{Wł. lub Wył. Mgłę Wojny - "symulację" widzenia oczyma kontolowanej postaci.}
{512}{}{Regulacja poziomu światła i funkcji "spójrz na" dla podłogi, ścian i dekoracji pod mgłą.}
{513}{}{Podłogi, ściany itd. zawsze będą widoczne a funkcja "spójrz na" będzie działać normalnie.}
{514}{}{Podłogi, ściany itd. zawsze będą zaciemnione a funkcja "spójrz na" nie będzie reagować, do czasu odkrycia.}
{515}{}{Kiedy włączona, przewijanie kamery od gracza jest nieograniczone. Najlepiej funkcjonuje z aktywną Mgłą Wojny.}
{516}{}{Zwiększenie wartości zwiększa odległość wyszukiwania drogi. 20 poziomów po 2000 jednostek.}
{517}{}{2000 jednostek (oryginalna wartość). UWAGA: każdy poziom wymaga dodatkowych 156.25 KB pamięci.}
{518}{}{40 000 jednostek. UWAGA: wymaga 3125 KB pamięci.}
{519}{}{Regulacja wyświetlania dla pewnych ekranów.}
{520}{}{Oryginalny rozmiar.}
{521}{}{Dopasowany do rozmiarów ekranu z jednoczesnym zachowaniem oryginalnych proporcji.}
{522}{}{Rozciągnięty do rozmiarów ekranu (wypełnienie).}
{523}{}{Kliknij poniżej aby zmienić wygląda bocznego paska.}
{524}{}{Zapisz i wyjdź.}
{525}{}{Wyjdź bez zatwierdzania.}
