{0}{}{Preferencias de juego}
{1}{}{Configuracion de pantalla}
{50}{}{Configuracion de pantalla}
{51}{}{Personalización}
{52}{}{Anchura}
{53}{}{Altura}
{54}{}{Hecho}
{55}{}{Cancelar}
{56}{}{Fallout debe reiniciar para aplicar los ajustes.}
{57}{}{¿Desea reiniciar Fallout ahora?}
{58}{}{Si}
{59}{}{No}
{60}{}{}
{100}{}{Alta-resolución}
{101}{}{RESOLUCIÓN}
{102}{}{Colores}
{103}{}{8 Bits}
{104}{}{16 Bits}
{105}{}{32 Bits}
{106}{}{Cambiar el arte de la barra lateral}
{107}{}{Invertir lista}
{108}{}{Modo ventana}
{109}{}{Tecla de desplazamiento}
{110}{}{Escalar X2}
{111}{}{Frecuencia de actualización}
{130}{}{Tecla de Windows}
{131}{}{Seleccionar}
{132}{}{Nombre}
{140}{}{Modo Grafico:}
{141}{}{Básico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Procesamiento de hardware de vértices:}
{149}{}{Versión de Shader 2.0:}
{150}{}{Escalado de paneles}
{151}{}{Ninguno}
{152}{}{Ajustar}
{153}{}{Rellenar}
{154}{}{Peliculas}
{155}{}{Splash}
{156}{}{Ayuda}
{157}{}{Muerte}
{158}{}{Diapositivas finales}
{159}{}{Menú principal}
{200}{}{Sfall}
{201}{}{ESCALAR-A: RES.}
{202}{}{MODO DX-9}
{203}{}{Apagado}
{204}{}{Pantalla completa}
{205}{}{Ventana}
{206}{}{GPU Blitting}
{207}{}{Esta configuración no tiene efecto en el Modo de Gráficos Básicos.}
{250}{}{Ignorar el límite de desplazamiento del PC}
{253}{}{Distancia máxima de desplazamiento}
{254}{}{Normal}
{255}{}{Máximo}
{256}{}{Habilitar Niebla de Guerra}
{257}{}{Visibilidad de niebla}
{258}{}{Oscuro}
{259}{}{Más claro}
{300}{}{Presiona una tecla o ESC para cancelar.}
{500}{}{Configuración del Hi-Res Patch.}
{501}{}{Configure la resolución de pantalla, el modo de color y la frecuencia de actualización para el modo de pantalla completa.}
{502}{}{Configure aquí la salida de color de pantalla completa.}
{503}{}{Configure aquí la frecuencia de actualización de pantalla completa. Establézcala en "0" para la configuración predeterminada del controlador.}
{504}{}{Personaliza el ancho de pantalla completa haciendo clic en el recuadro.}
{505}{}{Personaliza la altura de la pantalla completa haciendo clic en el recuadro.}
{506}{}{Activa o desactiva el Modo Ventana.}
{507}{}{En el modo ventana, esta es la tecla que mantendrás presionada cuando uses el mouse para desplazarte por el juego y los mapas del mundo.}
{508}{}{Presione el botón rojo para seleccionar una tecla diferente. O haga clic en el recuadro para editar el código de la tecla virtual de Windows.}
{509}{}{El nombre de la tecla seleccionada actualmente.}
{510}{}{Habilite el escalado X2. Esto también aumentará la resolución mínima a 1280x960. El modo Ventana requiere espacio para sus elementos.}
{511}{}{Activa o desactiva la Niebla de Guerra. Para obtener mejores resultados, activa esta opción antes de entrar al mapa por primera vez.}
{512}{}{Ajusta el nivel de brillo y del "mirar a" del ratón en suelos, paredes y escenarios bajo la niebla de guerra.}
{513}{}{Los suelos, paredes y escenarios siempre estarán visibles y la función "mirar a" del ratón funcionará con normalidad.}
{514}{}{Los suelos, paredes y escenarios estarán oscurecidos y la función "mirar a" del ratón NO funcionará hasta ser descubiertos.}
{515}{}{Cuando está habilitado, el desplazamiento alejándose del personaje es ilimitado. Funciona bien si la Niebla de Guerra está habilitada.}
{516}{}{Aumente la cantidad de nodos de búsqueda para ampliar la distancia de búsqueda de ruta. 20 niveles en incrementos de 2000 nodos.}
{517}{}{2000 nodos de búsqueda de ruta (valor original). Nota: Cada nivel requiere 156,25 KB de memoria adicional.}
{518}{}{40 000 nodos de búsqueda de ruta. Nota: requiere 3200 000 bytes (3125 KB) de memoria.}
{519}{}{Ajusta cómo se muestran determinadas pantallas.}
{520}{}{Tamaño original.}
{521}{}{Estirado para adaptarse al tamaño de la pantalla manteniendo la relación de aspecto original.}
{522}{}{Ampliado para llenar la pantalla. Nota: Si los subtítulos están habilitados, quedará un espacio en la parte inferior de la pantalla.}
{523}{}{Haz clic a continuación para alternar las opciones de la barra lateral de la interfaz del juego.}
{524}{}{Aplicar cualquier cambio y salir.}
{525}{}{Salir sin guardar.}
