{0}{}{Préférences de jeu}
{1}{}{Réglages de l'écran}
{50}{}{Réglages de l'écran}
{51}{}{Personnalisé}
{52}{}{Largeur}
{53}{}{Hauteur}
{54}{}{Valider}
{55}{}{Annuler}
{56}{}{Fallout doit redémarrer pour appliquer ces paramètres.}
{57}{}{Voulez-vous redémarrer Fallout maintenant ?}
{58}{}{Vrai}
{59}{}{Faux}
{60}{}{}
{100}{}{Haute résolution}
{101}{}{RESOLUTION}
{102}{}{Couleurs}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Modifier l'image de la barre latérale}
{107}{}{Inverser la liste}
{108}{}{Fenêtré}
{109}{}{Touche de défilement}
{110}{}{Mise à l'échelle X2}
{111}{}{Taux de rafraîchissement}
{130}{}{Window Key}
{131}{}{Select}
{132}{}{Nom}
{140}{}{Mode graphique :}
{141}{}{Basique}
{142}{}{Mode Sfall DirectX 9 :}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}
{150}{}{Mise à l'échelle du panneau}
{151}{}{Aucun}
{152}{}{Adapter}
{153}{}{Remplir}
{154}{}{Films}
{155}{}{Démarrage}
{156}{}{Aide}
{157}{}{Mort}
{158}{}{Fin}
{159}{}{Menu}
{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Off}
{204}{}{Plein écran}
{205}{}{Fenêtré}
{206}{}{GPU Blitting}
{207}{}{Ce paramètre n'a aucun effet en mode graphique de base.}
{250}{}{Ignore PC Scroll Limit}
{253}{}{Path Finding Range}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Autoriser le brouillard de guerre}
{257}{}{Visibilité du brouillard}
{258}{}{Sombre}
{259}{}{Plus lumineux}
{300}{}{PRESSER LA TOUCHE A ou ESC pour annuler.}
{500}{}{Paramètres du patch haute résolution.}
{501}{}{Configurer la résolution de l'écran, le mode couleur et le taux de rafraîchissement pour le mode plein écran.}
{502}{}{Setup the Fullscreen Colour output here.}
{503}{}{Définissez ici le taux de rafraîchissement du plein écran. Réglez cette valeur sur « 0 » pour le réglage par défaut du pilote.}
{504}{}{Personnalisez la largeur du plein écran en cliquant sur la case numérique.}
{505}{}{Personnalisez la hauteur du plein écran en cliquant sur la case numérique.}
{506}{}{Activer ou désactiver le mode fenêtré.}
{507}{}{En mode fenêtré, c'est la touche que vous devez maintenir enfoncée lorsque vous utilisez la souris pour faire défiler les cartes du jeu et du monde.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{Le nom de la touche actuellement sélectionnée.}
{510}{}{Activer la mise à l'échelle X2. Cela augmentera également la résolution minimale à 1280x960. Le mode fenêtre nécessitant plus d'espace pour son cadre.}
{511}{}{Enable or Disable Fog Of War. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Each level requires an additional 156.25 KB of memory.}
{518}{}{40 000 path search nodes. Note: requires 3200000 bytes (3125 KB) of memory.}
{519}{}{Adjust how certain screens are displayed.}
{520}{}{Original size.}
{521}{}{Stretched to fit the size of the screen while maintaining the original aspect ratio.}
{522}{}{Stretched to fill the screen. Note: A space will remain at the bottom of the screen if subtitles are enabled.}
{523}{}{Click below to cycle the in-game interface Side Bar options.}
{524}{}{Apply any changes and Exit.}
{525}{}{Quitter sans sauvegarder.}
