{0}{}{Preferenze di Gioco}
{1}{}{Impostazioni Schermo}
{50}{}{Impostazioni Schermo}
{51}{}{Personalizzato}
{52}{}{Larghezza}
{53}{}{Altezza}
{54}{}{Fatto}
{55}{}{Annulla}
{56}{}{Fallout deve essere riavviato per applicare le impostazioni.}
{57}{}{Vuoi riavviare ora Fallout?}
{58}{}{Vero}
{59}{}{Falso}
{60}{}{}
{100}{}{Alta-Risoluzione}
{101}{}{RISOLUZIONE}
{102}{}{Colori}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Cambia immagine inferiore}
{107}{}{Inverti Lista}
{108}{}{Finestra}
{109}{}{Set Scroll Key}
{110}{}{Ingrandisci X2}
{111}{}{Frequenza di Aggiornamento}
{130}{}{Window Key}
{131}{}{Seleziona}
{132}{}{Nome}
{140}{}{Modalità Grafica:}
{141}{}{Basica}
{142}{}{Modalità Sfall DirectX 9:}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Processione Vertex Hardware:}
{149}{}{Shader Versione 2.0:}
{150}{}{Scala Pannello}
{151}{}{Nessuno}
{152}{}{Riempi}
{153}{}{Riempi}
{154}{}{Filmati}
{155}{}{Schermata Iniziale}
{156}{}{Aiuto}
{157}{}{Morte}
{158}{}{Slides Finali}
{159}{}{Menu Principale}
{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Off}
{204}{}{Fullscreen}
{205}{}{Window}
{206}{}{GPU Blitting}
{207}{}{This setting has no effect while in Basic Graphics Mode.}
{250}{}{Ignore PC Scroll Limit}
{253}{}{Path Finding Range}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Enable Fog Of War}
{257}{}{Fog Visibility}
{258}{}{Dark}
{259}{}{Brighter}
{300}{}{PRESS A KEY or ESC to cancel.}
{500}{}{Hi-Res Patch settings.}
{501}{}{Setup the Screen Resolution, Colour mode and Refresh Rate for FullScreen Mode.}
{502}{}{Setup the Fullscreen Colour output here.}
{503}{}{Setup the Fullscreen Refresh Rate here. Set this to '0' for the driver default setting.}
{504}{}{Customize the Fullscreen Width by clicking the number box.}
{505}{}{Customize the Fullscreen Height by clicking the number box.}
{506}{}{Enable or Disable Window Mode.}
{507}{}{In Window Mode, this is the key you will hold down when using the mouse to scroll the Game and World maps.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{The name of the currently selected key.}
{510}{}{Enable X2 scaling. This will also up the min res to 1280x960. With Window mode requiring more space for its frame.}
{511}{}{Enable or Disable Fog Of War. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Each level requires an additional 156.25 KB of memory.}
{518}{}{40 000 path search nodes. Note: requires 3200000 bytes (3125 KB) of memory.}
{519}{}{Adjust how certain screens are displayed.}
{520}{}{Original size.}
{521}{}{Stretched to fit the size of the screen while maintaining the original aspect ratio.}
{522}{}{Stretched to fill the screen. Note: A space will remain at the bottom of the screen if subtitles are enabled.}
{523}{}{Click below to cycle the in-game interface Side Bar options.}
{524}{}{Apply any changes and Exit.}
{525}{}{Exit without saving.}
