{0}{}{Preferenze di Gioco}
{1}{}{Impostazioni Schermo}
{50}{}{Impostazioni Schermo}
{51}{}{Personalizzato}
{52}{}{Larghezza}
{53}{}{Altezza}
{54}{}{Fatto}
{55}{}{Annulla}
{56}{}{Fallout deve essere riavviato per applicare le impostazioni.}
{57}{}{Vuoi riavviare ora Fallout?}
{58}{}{Vero}
{59}{}{Falso}
{60}{}{}
{100}{}{Alta-Risoluzione}
{101}{}{RISOLUZIONE}
{102}{}{Colori}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Cambia immagine inferiore}
{107}{}{Inverti Lista}
{108}{}{Finestra}
{109}{}{Imposta tasto Blocco scorrimento}
{110}{}{Ingrandisci X2}
{111}{}{FREQ. AGGIORNAMENTO}
{130}{}{Tasto Window}
{131}{}{Seleziona}
{132}{}{Nome}
{140}{}{Modalita' Grafica:}
{141}{}{Basica}
{142}{}{Modalita' Sfall DirectX 9:}
{143}{}{}
{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}
{147}{}{Direct3D 9}
{148}{}{Processione Vertex Hardware:}
{149}{}{Shader Versione 2.0:}
{150}{}{Scala Pannello}
{151}{}{No}
{152}{}{Adatta}
{153}{}{Riempi}
{154}{}{Filmati}
{155}{}{Schermata Iniziale}
{156}{}{Aiuto}
{157}{}{Morte}
{158}{}{Slides Finali}
{159}{}{Menu Principale}
{200}{}{Sfall}
{201}{}{SCALA ALLA : RIS.}
{202}{}{MOD. DX-9}
{203}{}{Spento}
{204}{}{Pieno Schermo}
{205}{}{Finestra}
{206}{}{GPU Blitting}
{207}{}{Questa impostazioni non ha effetto quando si e' in modalita' Base.}
{250}{}{Ignora Limite di Scorrimento}
{253}{}{Distanza Percorribile}
{254}{}{Normale}
{255}{}{Max}
{256}{}{Abilita Nebbia di Guerra}
{257}{}{Visibilita' nebbia}
{258}{}{Coperto}
{259}{}{Scoperto}
{300}{}{PREMI UN TASTO o ESC per annullare.}
{500}{}{Impostazioni Hi-Res.}
{501}{}{Imposta la Risoluzione dello schermo, Colore e frequenza di aggiornamento per lo Schermo Intero.}
{502}{}{Imposta il Colore a Schermo Intero.}
{503}{}{Imposta la Frequenza di Aggiornamento. Imposta '0' per usare le impostazioni predefinite del driver.}
{504}{}{Personalizza la Larghezza a Pieno Schermo cliccando nella casella sottostante.}
{505}{}{Personalizza la Altezza a Pieno Schermo cliccando nella casella sottostante.}
{506}{}{Abilita o Disabilita la modalita' a Finestra.}
{507}{}{In modalita' Finestra, questo e' il tasto che dovrai tenere premuto per scorrere le schermante del Gioco e della Mappa.}
{508}{}{Premi il pulsante rosso per selezionare un tasto diverso. Oppure clicca sulla casella numerica per modificare il codice del tasto virtuale di Windows.}
{509}{}{Il nome del tasto attualmente selezionato.}
{510}{}{Abilita la scalatura X2. Questo aumentera' anche la risoluzione minima a 1280x960. Con la modalita' finestra che richiede più spazio per il suo bordo.}
{511}{}{Abilita o Disabilita la Nebbia di Guerra. Per i migliori risultati dovrebbe essere abilitata prima di entrare in una mappa per la prima volta.}
{512}{}{Regola il livello di luce e la visibilità 'guarda' del mouse per pavimenti, muri e scenari sotto la nebbia.}
{513}{}{Pavimenti, muri e scenari saranno sempre visibili e il Mouse "guarda" funzionerà normalmente.}
{514}{}{Pavimenti, muri e scenari saranno oscurati e non risponderanno al Mouse "guarda" finché non verranno scoperti.}
{515}{}{Quando abilitato, lo scorrimento lontano dal Personaggio del Giocatore è illimitato. Funziona bene se la Nebbia di Guerra è abilitata.}
{516}{}{Aumenta il numero di nodi di ricerca per estendere la distanza di ricerca del percorso. 20 livelli in incrementi di 2000 nodi.}
{517}{}{2000 nodi di ricerca del percorso (valore originale). Nota: Ogni livello richiede 156,25 KB aggiuntivi di memoria.}
{518}{}{40 000 nodi di ricerca. Nota: richiede 3200000 bytes (3125 KB) di memoria.}
{519}{}{Imposta come certe schermate si visualizzino.}
{520}{}{Dimensione originale.}
{521}{}{Allungata per riempire lo schermo mantenendo le proporzioni.}
{522}{}{Allungata per riempire lo schermo. Nota: uno spazio sarà visibile se i sottotitoli sono abilitati.}
{523}{}{Clicca sotto per scorrere le interfacce di gioco disponibili.}
{524}{}{Applica le modifiche ed Esci.}
{525}{}{Esci senza salvare.}
