name: Poify/Unpoify

on:
  push:
    paths:
      - "text/**"
  pull_request:
    paths:
      - "text/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Poify/Unpoify run
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: BGforgeNet/msg2po@master
        with:
          poify: true
          unpoify: true
          single_commit: true

      - name: Poify/Unpoify test
        if: (github.ref != 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request'
        uses: BGforgeNet/msg2po@master
        with:
          poify: true
          unpoify: true
          dir2msgstr: true
          push: false
